package com.rexaps.librex.rexcode.languages

import com.rexaps.librex.rexcode.*

abstract class Base(
    override val language: RexLanguage,
    override val extensions: Set<String>,
    override val keywords: Set<String> = emptySet(),
    override val types: Set<String> = emptySet(),
    override val lineComments: List<String> = emptyList(),
    override val blockComments: List<Pair<String,String>> = emptyList(),
    override val operators: Set<String> = emptySet(),
    override val fileNames: Set<String> = emptySet()
) : RexLanguageDefinition

private val C_LIKE = setOf("=", "+", "-", "*", "/", "%", "==", "!=", "===", "!==", "<", ">", "<=", ">=", "&&", "||", "!", "++", "--", "=>", "->", "?", "?:", "+=", "-=", "*=", "/=", "&", "|", "^", "~")
private val C_TYPES = setOf("int", "long", "short", "byte", "float", "double", "char", "string", "bool", "boolean", "void", "object", "var", "dynamic", "decimal", "uint", "ulong", "usize", "isize")

val JavaScriptSyntax = object : Base(RexLanguage.JAVASCRIPT, setOf("js","mjs","cjs"), setOf("const","let","var","function","return","class","extends","import","export","from","if","else","for","while","do","switch","case","break","continue","new","this","typeof","instanceof","in","of","try","catch","finally","throw","async","await","yield","get","set","static"), C_TYPES + setOf("Promise","Array","Object","String","Number","Boolean"), listOf("//"), listOf("/*" to "*/"), C_LIKE) {}
val TypeScriptSyntax = object : Base(RexLanguage.TYPESCRIPT, setOf("ts","mts","cts"), JavaScriptSyntax.keywords + setOf("interface","type","enum","namespace","implements","public","private","protected","readonly","abstract","declare","keyof","as","satisfies"), C_TYPES + setOf("unknown","never","any","interface","Record","Partial","Readonly"), listOf("//"), listOf("/*" to "*/"), C_LIKE) {}
val JavaSyntax = object : Base(RexLanguage.JAVA, setOf("java"), setOf("package","import","class","interface","enum","extends","implements","public","private","protected","static","final","abstract","void","return","new","this","super","if","else","for","while","do","switch","case","break","continue","try","catch","finally","throw","throws","synchronized","volatile","transient","instanceof","record","sealed","permits","var"), C_TYPES + setOf("String","Integer","Long","Double","Float","Boolean","Object","List","Map","Set"), listOf("//"), listOf("/*" to "*/"), C_LIKE) {}
val KotlinSyntax = object : Base(RexLanguage.KOTLIN, setOf("kt"), setOf("package","import","class","interface","object","data","sealed","enum","annotation","typealias","fun","val","var","const","return","if","else","when","for","while","do","break","continue","in","is","as","this","super","null","true","false","try","catch","finally","throw","by","get","set","constructor","init","override","open","final","private","protected","public","internal","suspend","inline","reified","where","operator","infix","tailrec"), C_TYPES + setOf("Any","Nothing","Unit","String","List","MutableList","Map","Set","Sequence"), listOf("//"), listOf("/*" to "*/"), C_LIKE) {}
val PythonSyntax = object : Base(RexLanguage.PYTHON, setOf("py","pyw","pyi"), setOf("def","class","return","if","elif","else","for","while","break","continue","in","is","not","and","or","lambda","yield","async","await","import","from","as","try","except","finally","raise","with","pass","match","case","global","nonlocal","assert","del"), setOf("str","int","float","bool","bytes","list","dict","set","tuple","object","type","None"), listOf("#"), listOf("'''" to "'''","\"\"\"" to "\"\"\""), C_LIKE) {}
val HtmlSyntax = object : Base(RexLanguage.HTML, setOf("html","htm"), setOf("doctype","html","head","body","script","style","div","span","a","img","button","form","input","meta","link","title","main","section","header","footer","nav"), emptySet(), listOf(), listOf("<!--" to "-->"), C_LIKE) {}
val CssSyntax = object : Base(RexLanguage.CSS, setOf("css"), setOf("important","media","supports","keyframes","font-face","import","layer","container"), setOf("px","em","rem","vh","vw","s","ms","deg","fr","auto","inherit","initial","unset","none","block","flex","grid"), listOf(), listOf("/*" to "*/"), C_LIKE) {}
val JsonSyntax = object : Base(RexLanguage.JSON, setOf("json"), emptySet(), emptySet(), emptyList(), emptyList(), setOf(":",",","{","}","[","]")) {}
val XmlSyntax = object : Base(RexLanguage.XML, setOf("xml","xsd","xsl","svg"), emptySet(), emptySet(), emptyList(), listOf("<!--" to "-->"), C_LIKE) {}
val CSyntax = object : Base(RexLanguage.C, setOf("c","h"), setOf("auto","break","case","const","continue","default","do","else","enum","extern","for","goto","if","inline","register","restrict","return","sizeof","static","struct","switch","typedef","union","volatile","while","_Atomic","_Bool","_Complex","_Generic","_Imaginary"), C_TYPES, listOf("//"), listOf("/*" to "*/"), C_LIKE) {}
val CppSyntax = object : Base(RexLanguage.CPP, setOf("cpp","cc","cxx","hpp","hh","hxx"), CSyntax.keywords + setOf("namespace","template","typename","using","public","private","protected","virtual","override","final","class","concept","requires","constexpr","consteval","noexcept","nullptr","operator","friend","new","delete","this","co_await","co_return","co_yield"), C_TYPES + setOf("std","string","vector","map","set","unordered_map","size_t"), listOf("//"), listOf("/*" to "*/"), C_LIKE) {}
val CSharpSyntax = object : Base(RexLanguage.CSHARP, setOf("cs"), setOf("using","namespace","class","struct","interface","enum","record","public","private","protected","internal","static","readonly","const","abstract","sealed","virtual","override","new","this","base","return","if","else","for","foreach","while","do","switch","case","break","continue","try","catch","finally","throw","async","await","lock","yield","is","as","in","out","ref","nameof","typeof","checked","unchecked"), C_TYPES + setOf("string","object","dynamic","Task","List","Dictionary","IEnumerable"), listOf("//"), listOf("/*" to "*/"), C_LIKE) {}
val GoSyntax = object : Base(RexLanguage.GO, setOf("go"), setOf("package","import","func","return","var","const","type","struct","interface","map","chan","go","defer","select","case","default","if","else","for","range","switch","fallthrough","break","continue","goto","return"), setOf("string","bool","byte","rune","int","int8","int16","int32","int64","uint","uint8","uint16","uint32","uint64","uintptr","float32","float64","complex64","complex128","error"), listOf("//"), listOf("/*" to "*/"), C_LIKE) {}
val RustSyntax = object : Base(RexLanguage.RUST, setOf("rs"), setOf("fn","let","mut","const","static","struct","enum","trait","impl","mod","use","pub","crate","self","super","where","for","in","if","else","match","loop","while","break","continue","return","async","await","move","ref","type","as","dyn","unsafe","extern","macro_rules","derive"), setOf("bool","char","str","String","i8","i16","i32","i64","i128","isize","u8","u16","u32","u64","u128","usize","f32","f64","Option","Result","Vec"), listOf("//"), listOf("/*" to "*/"), C_LIKE) {}
val PhpSyntax = object : Base(RexLanguage.PHP, setOf("php"), setOf("namespace","use","class","interface","trait","extends","implements","public","private","protected","static","final","abstract","function","return","if","else","elseif","for","foreach","while","do","switch","case","break","continue","try","catch","finally","throw","new","clone","echo","print","include","require","match","fn"), C_TYPES + setOf("mixed","callable","iterable","array","self","parent"), listOf("//","#"), listOf("/*" to "*/"), C_LIKE) {}
val SqlSyntax = object : Base(RexLanguage.SQL, setOf("sql"), setOf("select","from","where","and","or","not","insert","into","values","update","set","delete","create","alter","drop","table","view","index","join","inner","left","right","full","outer","on","group","by","order","having","limit","offset","union","all","distinct","as","case","when","then","else","end","primary","key","foreign","references","constraint","null","is","like","between","exists","with","recursive"), C_TYPES + setOf("text","varchar","timestamp","date","json","jsonb","uuid","serial"), listOf("--"), listOf("/*" to "*/"), C_LIKE) {}
val ShellSyntax = object : Base(RexLanguage.SHELL, setOf("sh","bash","zsh","fish"), setOf("if","then","else","elif","fi","for","while","in","do","done","case","esac","function","select","time","until","return","export","readonly","local","source","alias","unalias","set","unset","shift","trap","eval","exec"), emptySet(), listOf("#"), emptyList(), C_LIKE) {}
val YamlSyntax = object : Base(RexLanguage.YAML, setOf("yaml","yml"), setOf("true","false","null","yes","no","on","off"), emptySet(), listOf("#"), emptyList(), setOf(":","-","?","|",">","&","*","!","%","@","`")) {}
val MarkdownSyntax = object : Base(RexLanguage.MARKDOWN, setOf("md","markdown","mdown","mkdn"), setOf("true","false"), emptySet(), emptyList(), listOf("<!--" to "-->"), setOf("#","*","_","`","[","]","(",")","!",">","-")) {}
val DartSyntax = object : Base(RexLanguage.DART, setOf("dart"), setOf("abstract","as","assert","async","await","break","case","catch","class","const","continue","covariant","default","deferred","do","dynamic","else","enum","export","extends","extension","external","factory","final","finally","for","Function","get","hide","if","implements","import","in","interface","is","late","library","mixin","new","null","on","operator","part","required","rethrow","return","set","show","static","super","switch","sync","this","throw","true","try","typedef","var","void","while","with","yield"), C_TYPES + setOf("Future","Stream","Widget","List","Map","Set"), listOf("//"), listOf("/*" to "*/"), C_LIKE) {}
val SwiftSyntax = object : Base(RexLanguage.SWIFT, setOf("swift"), setOf("import","class","struct","enum","protocol","extension","func","init","deinit","var","let","if","else","guard","switch","case","default","for","while","repeat","in","where","break","continue","return","throw","throws","rethrows","try","catch","do","defer","async","await","actor","protocol","public","private","internal","fileprivate","open","static","final","override","self","super","nil","true","false"), C_TYPES + setOf("Any","AnyObject","String","Array","Dictionary","Set","Optional","Result"), listOf("//"), listOf("/*" to "*/"), C_LIKE) {}
val RubySyntax = object : Base(RexLanguage.RUBY, setOf("rb","rake","gemspec"), setOf("class","module","def","end","if","elsif","else","unless","case","when","while","until","for","in","do","begin","rescue","ensure","raise","return","yield","require","load","include","extend","attr_reader","attr_writer","attr_accessor","private","protected","public","lambda","proc","self","super","nil","true","false"), setOf("String","Integer","Float","Array","Hash","Symbol","Object","Module"), listOf("#"), emptyList(), C_LIKE) {}
val JsxSyntax = object : Base(RexLanguage.JSX, setOf("jsx"), JavaScriptSyntax.keywords, JavaScriptSyntax.types, listOf("//"), listOf("/*" to "*/"), C_LIKE) {}
val TsxSyntax = object : Base(RexLanguage.TSX, setOf("tsx"), TypeScriptSyntax.keywords, TypeScriptSyntax.types, listOf("//"), listOf("/*" to "*/"), C_LIKE) {}
val VueSyntax = object : Base(RexLanguage.VUE, setOf("vue"), TypeScriptSyntax.keywords, TypeScriptSyntax.types, listOf("//"), listOf("/*" to "*/"), C_LIKE) {}
val GradleSyntax = object : Base(RexLanguage.GRADLE, setOf("gradle"), setOf("plugins","repositories","dependencies","implementation","api","compileOnly","runtimeOnly","testImplementation","android","buildscript","allprojects","subprojects","group","version","rootProject","project","tasks","sourceSets","mavenCentral","google","gradlePluginPortal"), C_TYPES, listOf("//"), listOf("/*" to "*/"), C_LIKE) {}
val KtsSyntax = object : Base(RexLanguage.KTS, setOf("kts"), KotlinSyntax.keywords, KotlinSyntax.types, listOf("//"), listOf("/*" to "*/"), C_LIKE) {}
val TomlSyntax = object : Base(RexLanguage.TOML, setOf("toml"), setOf("true","false"), emptySet(), listOf("#"), emptyList(), setOf("=","[","]")) {}
val EnvSyntax = object : Base(RexLanguage.ENV, setOf("env"), setOf("true","false","null"), emptySet(), listOf("#"), emptyList(), setOf("=")) {}
val GitignoreSyntax = object : Base(RexLanguage.GITIGNORE, setOf(), emptySet(), emptySet(), listOf("#"), emptyList(), setOf("!","*","?","[","]"), setOf(".gitignore",".dockerignore")) {}
val DockerfileSyntax = object : Base(RexLanguage.DOCKERFILE, setOf(), setOf("FROM","RUN","CMD","LABEL","MAINTAINER","EXPOSE","ENV","ADD","COPY","ENTRYPOINT","VOLUME","USER","WORKDIR","ARG","ONBUILD","STOPSIGNAL","HEALTHCHECK","SHELL"), emptySet(), listOf("#"), emptyList(), setOf("\\","&&","||"), setOf("Dockerfile","dockerfile")) {}
val BatchSyntax = object : Base(RexLanguage.BATCH, setOf("bat","cmd"), setOf("echo","set","if","else","for","in","do","goto","call","start","shift","exit","setlocal","endlocal","enabledelayedexpansion"), emptySet(), listOf("rem","::"), emptyList(), setOf("&&","||","==","!=","<",">","|","&","^")) {}
val RSyntax = object : Base(RexLanguage.R, setOf("r","R"), setOf("if","else","repeat","while","function","for","in","next","break","TRUE","FALSE","NULL","NA","NaN","Inf","library","require","return","switch"), setOf("numeric","character","logical","integer","complex","list","data.frame","matrix","factor"), listOf("#"), emptyList(), C_LIKE) {}
val LuaSyntax = object : Base(RexLanguage.LUA, setOf("lua"), setOf("and","break","do","else","elseif","end","false","for","function","goto","if","in","local","nil","not","or","repeat","return","then","true","until","while","require","module"), setOf("string","number","boolean","table","function","thread","userdata"), listOf("--"), listOf("--[[" to "]]"), C_LIKE) {}
val ScssSyntax = object : Base(RexLanguage.SCSS, setOf("scss"), CssSyntax.keywords, CssSyntax.types, emptyList(), listOf("/*" to "*/"), C_LIKE + setOf("$","@mixin","@include","@extend","@use","@forward")) {}
val SassSyntax = object : Base(RexLanguage.SASS, setOf("sass"), CssSyntax.keywords, CssSyntax.types, emptyList(), listOf("/*" to "*/"), C_LIKE + setOf("$","@mixin","@include","@extend","@use","@forward")) {}
val LessSyntax = object : Base(RexLanguage.LESS, setOf("less"), CssSyntax.keywords, CssSyntax.types, emptyList(), listOf("/*" to "*/"), C_LIKE + setOf("@","~","$")) {}
val IniSyntax = object : Base(RexLanguage.INI, setOf("ini","cfg","conf"), setOf("true","false","yes","no","on","off","null"), emptySet(), listOf("#",";"), emptyList(), setOf("=",":")) {}
val TextSyntax = object : Base(RexLanguage.TEXT, setOf("txt","text"), emptySet(), emptySet(), emptyList(), emptyList(), emptySet()) {}
