package com.rexaps.librex.rexcode

enum class RexTokenType {
    KEYWORD, TYPE, FUNCTION, CLASS, VARIABLE, PROPERTY,
    STRING, STRING_ESCAPE, NUMBER, BOOLEAN, NULL,
    COMMENT, DOC_COMMENT, OPERATOR, PUNCTUATION, DELIMITER,
    TAG, TAG_NAME, ATTRIBUTE, ATTRIBUTE_NAME, ATTRIBUTE_VALUE,
    KEY, VALUE, ANNOTATION, DIRECTIVE, HEADING, LINK, CODE_BLOCK,
    CONSTANT, NAMESPACE, TEXT, UNKNOWN
}
